apiVersion: v1
appVersion: 1.3.3
description: Kiali is an open source project for service mesh observability, refer
  to https://www.kiali.io for details.
name: kiali
tillerVersion: '>=2.7.2'
version: 1.3.3
